import numpy as np
import os
import shutil

# load parameter list generated by LHS
# mu, n, k, m

paralist = np.loadtxt('Iso_lam_mu_k.txt')
nu = 0.4
tmp=121
for ParamVal in paralist:
	parfile = open('param.param','w')
	parfile.write('*PARAMETER\n')
	parfile.write('lam= ')
	parfile.write('%.3f\n'% ParamVal[0])
	parfile.write('mu= ')
	parfile.write('%.3f\n'% ParamVal[1])
	parfile.write('xn0_1=0.\n')
	parfile.write('xn0_2=0.\n')
	parfile.write('xn0_3=1.\n')
	parfile.write('kk= ')
	parfile.write('%.3f\n'% ParamVal[2])	
	parfile.write('tcrt=1.1982\n')
	parfile.write('mm=0.\n')	
	parfile.write('nn=0.\n')	
	parfile.write('t_init1=0.005\n')
	parfile.write('t_init2=0.05\n')
	parfile.write('t_max1=0.005\n')
	parfile.write('t_max2=0.05\n')
	parfile.close()
	os.system("abaqus job=JobName input=Iso_BC2 user=Iso_55cc ask_delete=OFF cpus=10 interactive")
	os.system("abaqus viewer noGUI=readODB.py")

	os.rename("JobName.sta", "job" + str(tmp)+ ".sta")
	os.rename("JobName.odb", "job" + str(tmp)+ ".odb")
	os.rename("JobName.pes", "job" + str(tmp)+ ".pes")
	os.rename("JobName1.txt", "job" + str(tmp)+ "thetag.txt")
	os.rename("JobName2.txt", "job" + str(tmp)+ "theta.txt")
	os.rename("JobName3.txt", "job" + str(tmp)+ "xcoord.txt")
	os.rename("JobName4.txt", "job" + str(tmp)+ "ycoord.txt")
	os.rename("JobName5.txt", "job" + str(tmp)+ "zcoord.txt")
	tmp += 1
	#os.rename("JobName.odb", "job_"+ str(int(ParamVal[0]*1000.))+"_"+ str(int(ParamVal[1]*1000.))+"_"+ str(int(ParamVal[2]*1000.)) +"_"+ str(int(ParamVal[3]*1000.)) + ".odb")
